version: '3.8'
services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./shared-volume:/var/data
    environment:
      - GF_INSTALL_PLUGINS=frser-sqlite-datasource
  microsense:
    build: .
    container_name: microsense
    ports:
      - '8000:8000'
    volumes:
      - ./shared-volume:/app/shared-volume
    environment:
      - MICROSENSE_DB_PATH=/app/shared-volume/microsense.db
      - MICROSENSE_API_KEY=123456    
      - PORT=8000

volumes:
  grafana-storage: {}
  shared-volume: